name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
#  check_commit:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Check commit
#        run: echo "✅ Commit checked."

  login_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build_and_push:
    runs-on: ubuntu-latest
    needs: login_dockerhub
    steps:
      - uses: actions/checkout@v4
      - name: Check commit
        run: echo "✅ Commit checked."
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: lucfzy/insure-app:latest
